### ISSUE TITLE
No validation property

### ISSUE THREAD

**Issue by devqcf** [enzotiezzi/masked_text_flutter#20]

**Comment by enzotiezzi** [comment]
Indeed, fixing it

**Comment by enzotiezzi** [comment]
PR actions for analyze and test is running for this PR, after complete, will merge with main and auto publish to pub


https://github.com/enzotiezzi/masked_text_flutter/pull/21

**Comment by enzotiezzi** [comment]
Merge complete

already publised to 
https://pub.dev/packages/masked_text 
v: 1.1.2

thanks for letting me know about this bug 

let me know if it's ok and if i can finish this issue
