### ISSUE TITLE
build error 

### ISSUE THREAD

**Issue by wackyapps** [enzotiezzi/masked_text_flutter#22]
masked_text-1.1.2/lib/masked_text.dart:94:13: Error: No named parameter with the name 'mouseCursor'.
            mouseCursor: mouseCursor,
            ^^^^^^^^^^^

**Comment by enzotiezzi** [comment]
Hello, i'm trying to reproduce the bug, but so far i couldn't, the property is still there, that's weird.

have you tried flutter clean after upgrading the version?
