### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by Arcrueid** [enzotiezzi/masked_text_flutter#4]
Any example for validate or read text value?

When I add a listener to the controller, and I execute a setState the text can not be deleted, the pointer stops in the "-" char with this mask "###########-#"

**Comment by enzotiezzi** [comment]
Sorry for the delayed answer

What version of the plugin are you using?
in 0.0.4 i already fixed the problem that was making the pointer stops on the symbols(for android and ios)

**Comment by enzotiezzi** [comment]
This is an example for birthday.

if you want to read the value of this.

just get the `text` property of your controller.

    TextEditingController _textController = new TextEditingController();

    new MaskedTextField
    (
        maskedTextFieldController: _textController,
        mask: "xx/xx/xxxx",
        maxLength: 10,
        keyboardType: TextInputType.number,
        inputDecoration: new InputDecoration(
        hintText: "birthday", labelText: "birthday"),
    );

    print(_textController.text);

you should get something like: `11/02/1995` or any other numbers you just typed

**Comment by enzotiezzi** [comment]
as it didn't have any other comment
