### ISSUE TITLE
This package cannot be used in flutter SDK 2.1.0-dev.0.0

### ISSUE THREAD

**Issue by Peraluna** [enzotiezzi/masked_text_flutter#5]
This package cannot be used in flutter SDK 2.1.0-dev.0.0. 
Could you please upgrade it ?

**Comment by enzotiezzi** [comment]
I'll fix it today, thanks for reporting :D

**Comment by enzotiezzi** [comment]
version 0.0.6 just published with the fix, sorry for not solving it before.
