### ISSUE TITLE
Backspacing after symbol doesn't work

### ISSUE THREAD

**Issue by DavisRayM** [enzotiezzi/masked_text_flutter#7]
If the inputted text is something like xx/xx/xxxx and one wants to delete to xx/xx the plugin doesn't respond and returns a string such as xx/xx/.

**Comment by DavisRayM** [comment]
Seems like `lastTextSize` is being [reset every build](https://github.com/enzotiezzi/masked_text_flutter/blob/master/lib/masked_text.dart#L34).

**Comment by enzotiezzi** [comment]
sorry for not answering too fast, i'll fix it.

**Comment by DineshBalayan** [comment]
still this issues i am facing, any solution
