### ISSUE TITLE
A couple existing TextField properties are not supported?

### ISSUE THREAD

**Issue by ElixirMike** [enzotiezzi/masked_text_flutter#9]
I want to use this, but it looks like it doesn't support all the properties of TextField.
Specifically, I'm using onEditingComplete and textInputAction.

Can you add that support in? I'm assuming you are just extending the existing TextField...so should be easy?

**Comment by htsnet** [comment]
Good. I need this too. Thanks.

**Comment by sayhicoelho** [comment]
I'm using the https://pub.dev/packages/mask_text_input_formatter that uses the native TextField widget. Working fine!

**Comment by htsnet** [comment]
@sayhicoelho Thank you for sharing. I changed to this package and it is working well.
